[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "html2tree"
version = "0.0.0"
description = "CLI for html2tree"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

[project.scripts]
html2tree = "html2tree.cli:main"
